# Generated by Django 4.1.4 on 2023-01-04 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domains',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('start', models.IntegerField()),
                ('stop', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Organisms',
            fields=[
                ('taxa_id', models.IntegerField(primary_key=True, serialize=False)),
                ('clade', models.CharField(max_length=10)),
                ('genus', models.CharField(max_length=100)),
                ('species', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pfam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('domain_id', models.CharField(max_length=100)),
                ('domain_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Proteins',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('protein_id', models.CharField(max_length=100)),
                ('sequence', models.TextField()),
                ('length', models.IntegerField()),
                ('taxa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protein.organisms')),
            ],
        ),
        migrations.CreateModel(
            name='ProteinDomain',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('domains_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protein.domains')),
                ('proteins_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protein.proteins')),
            ],
        ),
        migrations.AddField(
            model_name='domains',
            name='pfam_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protein.pfam'),
        ),
        migrations.AddField(
            model_name='domains',
            name='proteins_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protein.proteins'),
        ),
    ]
