# Generated by Django 4.1.4 on 2023-01-07 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domains',
            old_name='proteins_id',
            new_name='protein_id',
        ),
    ]
